name: Check software list changes

# Triggers the workflow on push or pull request events
on:
  push:
    paths: software/README.md
  pull_request:
    paths: software/README.md

env:
  list: "software"

jobs:
  checker:
    name: Table checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Download current version
        run: | 
          for i in ${{ env.list }};
          do
            curl https://raw.githubusercontent.com/NCSC-NL/spring4shell/main/${i}/README.md -o software_list_main_${i}.md
          done
      - name: Get pwd and list files
        run: pwd && ls -la
      - name: Create diff log
        # Circumvent early exit as there are changes
        run: | 
          for i in ${{ env.list }};
          do
            (git diff --no-index software_list_main_${i}.md ${i}/README.md || true ) > diff_${i}.log
          done
      - name: List files
        run: ls -la
      - name: Print diff
        # Print diff
        run: cat diff_*.log
      - name: Check table
        # Check only added lines
        run: python3 .github/check_valid.py `ls diff_*.log`
